### ISSUE TITLE
Add replication factor into kafkactl get topics

### ISSUE THREAD

**Issue by gurchenkov** [deviceinsight/kafkactl#105]
Hello,
Its possible to add topic **Replication Factor** into **kafkactl get topics** output?
Seems to be usefull.
Thanks!

**Comment by felix786** [comment]
@gurchenkov A replication factor of N allows you to control the topic reliability. Higher replication factor leads to higher availability.  Assume topics had replication factor of three, meaning that each partition is replicated three times on three different brokers. If the topic crucial we can create that topic with more replication factor.
