### ISSUE TITLE
"topic % does not exist" error is given even when topic auto creation is enabled

### ISSUE THREAD

**Issue by vchslv13** [deviceinsight/kafkactl#106]
Trying to produce a message to the non-existent topic gives a "topic % does not exist" error in any case (seems that the logic responsible for this is [here](https://github.com/deviceinsight/kafkactl/blob/988639d8a291971ff73ba9a79140fa7f482ef55f/operations/topic-operation.go#L261) ) while it should be actually possible to do this if `auto.create.topics.enable` is true in kafka config.

P.S. Thanks for the great CLI tool, btw. It's quite handy to use for pet projects as well as for the "real" work :)

**Comment by random-dwi** [comment]
hey,
please provide verbose logs from your produce command (`kafkactl produce -V`) as well as the version of the kafka cluster you are running against.

**Comment by vchslv13** [comment]
OK, here you go.

I'm using Confluent Kafka 6.1.0 - that should be compatible with Apache Kafka 2.7 ([see here](https://docs.confluent.io/platform/current/installation/versions-interoperability.html)).

kafkactl output:
```
[slava@slava-thinkpad-e14 kasta-test-task]$ kafkactl produce non-existent -v "test" -V
[kafkactl] 2021/11/04 23:51:01 Using config file: /home/slava/.config/kafkactl/config.yml
[kafkactl] 2021/11/04 23:51:01 Assuming kafkaVersion: 2.0.0
[kafkactl] 2021/11/04 23:51:01 Assuming kafkaVersion: 2.0.0
[kafkactl] 2021/11/04 23:51:01 using default admin request timeout: 3s
[sarama  ] 2021/11/04 23:51:01 Initializing new client
[sarama  ] 2021/11/04 23:51:01 client/metadata fetching metadata for all topics from broker localhost:29092
[sarama  ] 2021/11/04 23:51:01 Connected to broker at localhost:29092 (unregistered)
[sarama  ] 2021/11/04 23:51:01 client/brokers registered new broker #1001 at localhost:29092
[sarama  ] 2021/11/04 23:51:01 Successfully initialized new client
topic 'non-existent' does not exist
```

Same thing done from clojure client works fine:
```
clj꞉kasta-test-task.core꞉> 
(require '[jackdaw.client :as jc])
nil
clj꞉test.core꞉> 
(def producer-config
  {"bootstrap.servers" "localhost:29092"
   "key.serializer" "org.apache.kafka.common.serialization.StringSerializer"
   "value.serializer" "org.apache.kafka.common.serialization.StringSerializer"
   "client.id" "test"})
#'test.core/producer-config
clj꞉test.core꞉> 
(with-open [my-producer (jc/producer producer-config)]
  @(jc/produce! my-producer {:topic-name "non-existent"} "test"))
{:topic-name "non-existent", :partition 0, :timestamp 1636062878165, :offset 0, :serialized-key-size -1, :serialized-value-size 4}
```

**Comment by random-dwi** [comment]
version `1.23.0` was just released and contains a fix. We no longer check if the topic exists and let kafka handle it.
when topic auto creation is disabled the error message will then come directly from kafka and looks like this:

```
./kafkactl produce non-existent -v "test"
Failed to produce message: kafka server: Request was for a topic or partition that does not exist on this broker.
```

**Comment by vchslv13** [comment]
Great! Thank you so much :)
