### ISSUE TITLE
Protobuf support

### ISSUE THREAD

**Issue by xakep666** [deviceinsight/kafkactl#110]
Currently I use this utility for all my needs. But it can't read topics with protobuf-encoded messages. It seems that [https://github.com/jhump/protoreflect/](protoreflect) may parse raw proto IDL-s and should help with this feature.

**Comment by random-dwi** [comment]
Hi @xakep666,
this is an interesting feature. Sadly we currently don't have the resources to implement it.
But, if you are willing to work on this we can support you if needed. In general the implementation should be similar to the avro message deserialization which is already implemented.
See [AvroMessageDeserializer.go](https://github.com/deviceinsight/kafkactl/blob/master/internal/consumer/AvroMessageDeserializer.go) for a point to start.
