### ISSUE TITLE
Support for schema registries URL containing path prefix

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [deviceinsight/kafkactl#118]
Hello

This tool assumes that schema registry url is always a URL address without context path, i.e. `http://localhost` or `https://my.registry.org`

But, alternative implementations of confluent compatible schema registries, e.g. [Apicurio Registry](https://www.apicur.io/registry/) may expose API with URL context path. E.g.  `http://apcrg.localhost/apis/ccompat/v6`

So, currently this tool produces an error, when attempting to configure URL with context path as a schema registry URL, because the tool add port and schema to the configured URL. 

```
failed to list available avro schemas: client: (: ) failed with error code 0RESTEASY003210: Could not find resource for full path: http://apcrg.localhost/apis/ccompat/v6:80/subjects
```

Instead the tool should analyze configured schema registry URL to understand if it has context path or not, before adding default port `80`.

**Comment by d-rk** [comment]
Hey @ievgenii-shepeliuk,

we currrently use https://github.com/lensesio/schema-registry for avro, which is deprecated and should be exchanged to somthing else in the near future.

Looking at the at the [code of the schema registry](https://github.com/lensesio/schema-registry/blob/50a5701c1891dabf97cf5904c4b3a6761d7367d9/client.go#L84) you could try to add a port to your registry as a workaround. Somthing like: `http://apcrg.localhost:80/apis/ccompat/v6`

**Comment by ievgenii-shepeliuk** [comment]
Thanks for suggestion, worked.
