### ISSUE TITLE
Support for from-timestamp message consumption

### ISSUE THREAD

**Issue by pierre-degrandmaison** [deviceinsight/kafkactl#121]
Converting timestamp to topic/partition offset is not easy without coding.... a nice new feature would be to be able to consume messages by providing from-timestamp, and let the kafkactl code compute the corresponding start offset value.

**Comment by d-rk** [comment]
Hey @pierre-degrandmaison 
I already thought about this and implementing it would be not that complicated.

In this [method](https://github.com/deviceinsight/kafkactl/blob/a34110c6ad76ea864bd6bfaad41592ecc33e2ca7/internal/consume/PartitionConsumer.go#L135) one could determine the start offset with:
```
oldestOffset, err = (*client).GetOffset(topic, partition, fromTS)
```
So if you are willing to work on it, a PR is always welcome 😃 

Cheers

**Comment by nanic** [comment]
Hi @d-rk, Please let me know if you think the changes are enough and if i am missing anything. I did notice the timeout issue referred in #67 .

**Comment by pierre-degrandmaison** [comment]
Works great! very useful, thank you
