### ISSUE TITLE
Possibility to produce avro encoded message to schema registry powered topic

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [deviceinsight/kafkactl#123]
Hello

Some tools allow to produce Avro encoded messages to a topic, using schema from schema registry, with *pure JSON* file as input message.

For example this https://github.com/tchiotludo/akhq

**Comment by d-rk** [comment]
Hi @ievgenii-shepeliuk,

I'm sorry but I don't see what you are aiming at.
Since we already support avro schemas, can you elaborate a bit on what extension you propose?

Cheers

**Comment by eshepelyuk** [comment]
Hello @d-rk, sorry for late response, this is a wider explanation of the improvement.

### Use case with errors

1. The schema 
```json
{
  "name": "CreateUserProfileWallet",
  "namespace": "Messaging.Contracts.WalletManager.Commands",
  "type": "record",
  "fields": [
    { "name": "CurrencyCode", "type": "string" },
    { "name": "ExpiresOn", "type": ["null", "string"] }
  ]
}
```
2. First JSON, where `ExpiresOn` = null
    ```json
    { 
      "CurrencyCode": "EUR" 
    }
    --
    ```
    `kafkactl` invocation and the output
    ```
    kafkactl produce create_user_profile_wallet -f create-null.json -L '--'
    Failed to produce message: failed to convert value to avro data: cannot decode textual record 
    "Messaging.Contracts.WalletManager.Commands.CreateUserProfileWallet": only found 1 of 2 fields    
    ```
3. Second JSON, where `ExpiresOn` != null
    ```json
    {
      "CurrencyCode": "EUR",
      "ExpiresOn": "2022-12-12"
    }
    --
    ```
    `kafkactl` invocation and the output
    ```
    kafkactl produce create_user_profile_wallet -f create.json -L '--'
    Failed to produce message: failed to convert value to avro data: cannot decode textual record 
   "Messaging.Contracts.WalletManager.Commands.CreateUserProfileWallet": cannot decode textual union: expected: '{'; actual: '"' for key: "ExpiresOn"
    ```
    
So, the messages are not working with `kafkactl` but those files are valid Avro JSON messages and can be sent to a topic using some other tools, e.g. AKHQ.
    
### Existing solution

To overcome a problem - JSON files must be changed to some unfriendly format.

1. First JSON, where `ExpiresOn` == null
    ```json
    {
      "CurrencyCode": "EUR",
      "ExpiresOn": {
        "null": null
      }
    }
    --
    ```
2. Second JSON, where `ExpiresOn` != null
    ```json
    {
      "CurrencyCode": "EUR",
      "ExpiresOn": {
       "string": "2022-12-12"
     }
    }
    --
    ```
    
### Improvement request    

As a user I'd like `kafkactl` to be able to handle _plain_ JSON (as described in the _Use case_ section) for producing Avro encoded message.
Without need to convert my _plain_ JSON to that `weird` format.
Currently this is working for some other tools, e.g. AKHQ UI, but it is missing for CLI based tools.

**Comment by d-rk** [comment]
Hey @eshepelyuk 

we are using https://github.com/linkedin/goavro for the avro de/serialization.

If you want to omit fields in the json you can specify a default in the schema:
```
{
  "name": "CreateUserProfileWallet",
  "namespace": "Messaging.Contracts.WalletManager.Commands",
  "type": "record",
  "fields": [
    { "name": "CurrencyCode", "type": "string" },
    { "name": "ExpiresOn", "type": ["null", "string"], "default": null}
  ]
}
```

With this schema your first use-case should work.

For the second use-case check this issue: https://github.com/linkedin/goavro/issues/106.
In the issue it is mentioned that this is according to the avro spec: https://avro.apache.org/docs/current/spec.html#json_encoding

So I guess there is not much we can do here.

**Comment by eshepelyuk** [comment]
Hello @d-rk 

I've been able to advance on the issue using small python program that leverages [fastavro](https://github.com/fastavro/fastavro) python library.

So my script is able to create _AVRO json_ ( i.e. weird JSON with types ) from _plain JSON_. Then resulting _AVRO JSON_ can be sent to kafka using `kafkactl`.

Attaching a new archive containing the script. Plz install fastavro with pip to use it. 
[json2avro.zip](https://github.com/deviceinsight/kafkactl/files/8592421/json2avro.zip)
 
Script can be used like this

```sh
./json2avro.py create-null.json | kafkactl produce create_user_profile_wallet
```
Could you take a look and check if your libraries support the same functionality, so it can be eventually implemented in `kafkactl` ?

**Comment by d-rk** [comment]
Hey @eshepelyuk 

I saw that the latest [goavro version](https://github.com/linkedin/goavro/releases/tag/v2.11.0) supports ingesting standard json directly instead of avro json format.

I already tested it out, but sadly it only works for encoding of avro messages and not for the decoding of avro messages.
I filed an issue about that https://github.com/linkedin/goavro/issues/247, but I will probably wait until decoding to standard json also works before integrating it in kafkactl.

**Comment by xmcqueen** [comment]
I see this mention over here too.  Thanks you two.

**Comment by eshepelyuk** [comment]
Hello 
The goavro issue is closed. Any updates on this issue ?

**Comment by ievgenii-shepeliuk** [comment]
@d-rk Release 3.0 failed, so this feature is not yet released.

**Comment by d-rk** [comment]
![](https://media.giphy.com/media/tZ4QzCueTwh2g/giphy.gif)
