### ISSUE TITLE
Cannot produce long messages

### ISSUE THREAD

**Issue by rogelio-o** [deviceinsight/kafkactl#124]
**Context:** When trying to produce long messages, `kafkactl` always prints "0 messages produced" and produce no messages with no errors. I have configured `max-message-bytes` to `8000000`.

**Problem:** The `scanner.Scan()` is not returning any message when scanning stdIn or file because the message does not fit in the scanner buffer.

**Solution:** changes the size of the buffer by one in which the message fits when creating the scanner.

`producer-operation.go:184`
```
		scanner := bufio.NewScanner(inputReader)
		if config.Producer.MaxMessageBytes > 0 {
			scanner.Buffer(make([]byte, 0, config.Producer.MaxMessageBytes), config.Producer.MaxMessageBytes)
		}
```

**Comment by d-rk** [comment]
Hey @rogelio-o 
thank your for investigating this. a new version with a fix (2.2.1) has just been released.
