### ISSUE TITLE
Consuming a "tombstones" message from Protobuf topic skips the message with an error

### ISSUE THREAD

**Issue by Kostassoid** [deviceinsight/kafkactl#129]
Hello,

we use Protobuf for both keys and values in topics. `kafkactl` handles both fine with `--proto-file`, `--proto-import-path`, `--key-proto-type` and `--value-proto-type` params. However, for compacted topics, `null` messages (aka tombstones) result in `kafkactl` printing a single `Proto parse warning: %!s(<nil>)` to stderr without any additional info.

Expected behavior for us would be seeing a key and headers still printed perhaps with some special value for the empty payload.

**Comment by d-rk** [comment]
@Kostassoid [v2.4.0](https://github.com/deviceinsight/kafkactl/releases/tag/v2.4.0) with the fix for this issue has just been released.
