### ISSUE TITLE
Deleting multiple topic at once by regexp

### ISSUE THREAD

**Issue by hyzyla** [deviceinsight/kafkactl#135]
I have a group of topics with some prefix and would like to delete them by one command. Something similar to this:

```shell
./bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic 'service1-.*'
```

**Comment by d-rk** [comment]
Thats currently not supported. But on linux you could do something like this (untested): 

```
kafkactl get topics -o compact | grep service1- | xargs -I {} kafkactl delete topic {}
```
