### ISSUE TITLE
Unable to provide multiple values for broker via env variable

### ISSUE THREAD

**Issue by mlasevich** [deviceinsight/kafkactl#140]
Using kafkactl via docker container and when passing `BROKERS="broker1:9094,broker2:9094"` I get error that boils down to: `too many colons in address` . I thin it is not parsing this as a list, but instead treating it as  one host/port combination.

Is there a proper way to pass a list of hosts via a variable?

**Comment by d-rk** [comment]
Hey @mlasevich ,

I just updated the readme to clarify this. You can use whitespace as delimiter e.g.:
```
docker run --env BROKERS="kafka1:9092 kafka2:9092" deviceinsight/kafkactl:latest get brokers
```

just out of curiosity i would like to know how you use kafkactl in docker. where is your kafka cluster running? in kubernetes?
