### ISSUE TITLE
Consume from a Topic and produce to another

### ISSUE THREAD

**Issue by gmiano** [deviceinsight/kafkactl#141]
Hello,
I find your tool very useful and complete for my purposes and I want to thank you for that.
 I have one question I did not find an answer autonomously. I would like to retrieve events from a DLQ topic and after a manual check I would like to submit them again to the original topic, passing even headers.
 I tried to consume messages with headers in json format but I found no way to resubmit them.

**Comment by d-rk** [comment]
Hey  @gmiano ,

this is currently not possible.
at the moment only messages with key and value can be produced and only in a csv format.

The relevant code block begins here: https://github.com/deviceinsight/kafkactl/blob/main/internal/producer/producer-operation.go#L193

It would be a good enhancement to support also json input for the produce command, but currently I cannot estimate when we have capacity to implement it.

If you are willing to work on it however, PRs are always welcome :)
