### ISSUE TITLE
get topics command should not require describe permission depending on output format

### ISSUE THREAD

**Issue by JamesDunne** [deviceinsight/kafkactl#151]
We have a service account with very limited permissions that we're using to access our kafka cluster. Specifically, it is missing the `describe` permission on all topics.

When using `get topics`, if the output format is `compact` then the `describe` permission is not required and the call will succeed. For most other output formats like `json`, the `describe` permission is required due to extra properties being requested by that output format which will cause the `get topics` command to fail with `failed to describe topic config: Topic authorization failed` errors.

In our opinion, the output format alone should not dictate the set of properties chosen for output and by extension possibly require extra permissions to fetch. Ideally, that should be a separate option to allow for adding more properties which require the `describe` permission to fetch. Alternatively, `get topics` could degrade gracefully if the `describe` operation fails with an authorization failed error.

**Comment by d-rk** [comment]
hey @JamesDunne 
I agree that this is not ideal. The command should not fail depending on the output format. The additional properties are added for convenience and most people probably aren't in an environment as restricted as yours. So I would suggest to keep the output like it is, but degrade gracefully if describing the topic fails.

The issue however does not affect that many people and therefore will not have very high priority for us. But a PR is always welcome.
