### ISSUE TITLE
Kafkactl fails changing topic config using kubernetes

### ISSUE THREAD

**Issue by pando85** [deviceinsight/kafkactl#158]
It fails trying to change topic configuration through Kubernetes container.

```bash
kafkactl version
cmd.info{version:"v3.2.0", buildTime:"2023-08-17T05:13:30Z", gitCommit:"0b74c26", goVersion:"go1.20.7", compiler:"gc", platform:"linux/amd64"}
```

```
$ kafkactl alter topic demo --config 'retention.ms=86400000'
Could not alter topic config 'demo': Unknown topic config name: [retention.ms
pod demo/kafkactl-dummy terminated (Error)
```

It works using the `attach` command and then running the same command locally.

**Comment by d-rk** [comment]
Hey @pando85 
can you run the command with verbose output (`-V`)? This will output the actual `kubectl` command which is used.
This should help to resort the problem.

**Comment by pando85** [comment]
Hello @d-rk ,

I guess that the problem is here:
```
[kafkactl] 2023/08/22 09:33:41 exec: kubectl run --rm -i --tty --restart=Never kafkactl-dummy --image deviceinsight/kafkactl:v3.2.0-scratch --context demo --namespace demo --env BROKERS=demo-kafka:9092 --env REQUESTTIMEOUT=0s --env KAFKAVERSION=3.3.1 --env AVRO_SCHEMAREGISTRY=kafka-sr:8081 --env AVRO_JSONCODEC=standard --command -- /kafkactl alter topic demo --config=[retention.ms=86400000] --verbose=true
```

**Comment by d-rk** [comment]
I guess it is the brackets around `[retention.ms=86400000]`, but I will have to take a closer look.

**Comment by trescube** [comment]
I'm seeing the same issue, with kubernetes, the command appears to wrap square brackets around the value supplied in `--config`/`-c`:

`37: --config=[retention.ms=10000] (29 bytes)`

**Comment by trescube** [comment]
If I execute with the `-V` flag for verbose:

```sh
kafkactl alter topic <my_topic> -V --config cleanup.policy=compact
```

 it dumps the kubectl command being executed which ends with:

```
--command -- /kafkactl alter topic <my_topic> --config=[cleanup.policy=compact] --verbose=true
```

and shows the error:

`Could not alter topic config '<my_topic>': Unknown topic config name: [cleanup.policy`

If I take the kubectl command and run manually but remove the enclosing square brackets, it works as expected and alters the config.

Interestingly, if add a second `--config` option:

```sh
kafkactl alter topic <my_topic> -V --config cleanup.policy=compact --config retention.ms=1234
```

I get `config has been altered` returned but the changes aren't actually made and the executed kubectl command looks like:

```
--command -- /kafkactl alter topic <my_topic> --config=[cleanup.policy=compact,retention.ms=1234] --verbose=true
```

If I take this kubectl command and expand the single combined `--config` to `--config=cleanup.policy --config compact,retention.ms=1234`, then it works as expected.

This leads me to think that the initial `kafkactl` command with 2 `--config` parameters are being joined, then then never expanded again when sent to the kubernetes pod.

**Comment by d-rk** [comment]
version 3.4.0 was just released and should fix the issue.

**Comment by trescube** [comment]
Confirmed that 3.4.0 does fix the issue.
