### ISSUE TITLE
Can't execute multiple commands in parallel - kubernetes config

### ISSUE THREAD

**Issue by DaspawnW** [deviceinsight/kafkactl#165]
Hi,

first of all thanks a lot for this great tool!!

As one of the use cases I run in parallel a consumer & a producer to verify if the work is doing what it should.
Now I detected this great feature to run the tasks streight inside kubernetes instead of running the commands in a self build pod that crashes from time to time :-)

It turns out that the parallel consuming and producing is not possible as it tries to create two times the same pod and fails with a kubectl exception `pods "kafkactl-root" already exists`.

I checked the sources and it seems that the pod name can only be overwritten to be random if the clientID is empty: https://github.com/deviceinsight/kafkactl/blob/35144d346c2de532b9b1fc94fef014aea6de1fe4/internal/k8s/executor.go#L124-L126

It runs out that even though I try to explicitly set `clientID: ""` within the kafkactl.yml the clientID IMHO never gets empty as then the default kicks in: 
https://github.com/deviceinsight/kafkactl/blob/main/internal/common-operation.go#L204-L219

Is there maybe a plan to make the podname in general random or via a boolean randomizable?

Thanks a lot!

**Comment by d-rk** [comment]
version 3.4.0 was just released and should fix the issue.
