### ISSUE TITLE
Allow reset of Kafka lag by time

### ISSUE THREAD

**Issue by ayushghosh** [deviceinsight/kafkactl#169]
Reset offsets to offset from datetime. Format: ‘YYYY-MM-DDTHH:mm:SS.sss’

kafka-consumer-groups.sh --bootstrap-server kafka-host:9092 --group my-group --reset-offsets
**--to-datetime 2020-11-01T00:00:00Z** --topic sales_topic --execute

Can we add this feature, as most time we want to reset by time.

**Comment by d-rk** [comment]
Hey @ayushghosh 

the feature would be useful indeed. If you are willing to contribute, a PR for this is welcome :)

The implementation should be relatively straight forward. You can get the offset from a timestamp with this:
[                return (*client).GetOffset(topic, currentPartition, fromUnixMillis)](https://github.com/deviceinsight/kafkactl/blob/main/internal/consume/PartitionConsumer.go#L189)

Regards,
Dirk

**Comment by nanic** [comment]
Hi @d-rk, added changes to reset by date time/timestamp(epoch). Please review and share any feedback. I had to modify `ParseTimestamp` to adjust for location(if not defaults to UTC) in parsing date time to timestamp(epoch).
