### ISSUE TITLE
Is it possible to use custom serdes classes with kafkactl to consume topics?

### ISSUE THREAD

**Issue by govardha** [deviceinsight/kafkactl#173]
Hello,

Thank you for a wonderful tool, we use it almost everyday.  I am new to kafka.  Is it possible to use kafkactl with a custom serdes, we are able to use the kafka included shell scripts with this to dump messages.  I was wondering if I can extend what we do there to the kafakctl utility?  This is a proprietary binary format.

Thank you!
gov

**Comment by d-rk** [comment]
Hey @govardha 

how do you imagine this to be implemented?
For the java clients you can add a deserializer to the classpath and configure the client to use it.
Thats not possible, so we would need some way to plug in the deserializer.
The deserializer would probably have to be written in go also.

Regards,
Dirk

**Comment by govardha** [comment]
Hello Dirk,

Thanks much for that clarification.  I now get the limitation of doing ser/des using an external java class inside this in go.  Without my rewriting the ser/des in go, I am not getting anywhere.  

Thanks for the clarification and thanks for an amazing tool.

gov
