### ISSUE TITLE
Breaking change in 3.5.1

### ISSUE THREAD

**Issue by staktrace** [deviceinsight/kafkactl#176]
Hi,

I upgraded kafkactl in my project from 3.4.0 to 3.5.1 and this command that I was running started to break:

```
kafkactl produce orc_test_input \
    -H "Content-Type: application/json" \
    -H "ce_specversion:1.0" \
    -H "ce_id:00001" \
    -H "ce_source:test-source" \
    -H "ce_type:type" \
    -H "ce_time:2021-08-26T00:24:10.01383Z" \
    -H "ce_partitionkey:partition-key" \
    -H "ce_datacontenttype:application/json" \
    -v '{"value": 42}'
```

Previously it would work fine, but after upgrading it emits this:

```
Failed to open Kafka producer: kafka: client has run out of available brokers to talk to: EOF
```

I bisected kafkactl and it appears to be coming from the dependency upgrade for `github.com/IBM/sarama` from `v1.40.1` to `v1.42.1`

**Comment by staktrace** [comment]
Seems to be because of the breaking changes in sarama `v1.41.0` ([link](https://github.com/IBM/sarama/releases/tag/v1.41.0)). Not sure if you want to roll back to the old sarama or are ok with having breaking changes here.

**Comment by staktrace** [comment]
Also FWIW we're using the `vectorized/redpanda:v22.3.11` docker image as a kafka implementation in this scenario.

**Comment by staktrace** [comment]
So for what it's worth, even using the latest redpanda image (`redpandadata/redpanda:v23.2.17`) I get the same error.

**Comment by d-rk** [comment]
closing stale issue.
