### ISSUE TITLE
Can I duplicate topics and its contents?

### ISSUE THREAD

**Issue by govardha** [deviceinsight/kafkactl#178]
Has anybody use kafkactl to copy & duplicate a topic?  The task at hand is to rename a topic, but I would rather duplicate & clone a topic and further delete once I validate the data is good.

Thank you!

**Comment by d-rk** [comment]
Hi @govardha 

How about https://github.com/deviceinsight/kafkactl/blob/main/README.md#clone-topic ?

**Comment by govardha** [comment]
Alas I did try it but that just created the topic with the partitions etc but did not copy over the contents of the topic.  Hence I posted here.

**Comment by d-rk** [comment]
closing this one, since #202 is very similar and we can track it there.
