### ISSUE TITLE
Topic creation should use default replication factor rather than 1

### ISSUE THREAD

**Issue by cykl** [deviceinsight/kafkactl#180]
When kafkactl creates a topic, it set replication-factor to 1 if not set by the user:

```go
cmdCreateTopic.Flags().Int16VarP(&flags.ReplicationFactor, "replication-factor", "r", 1, "replication factor")
```

To me, it violates the principle of least astonishment as most tools would pass `-1` meaning _use the default replication factor set at broker level_. I could lead to under replication alerts as actual replication (1) is likely smaller than `min.insync.replicas`.

Was 1 a deliberate choice? Would you agree changing the default value to `-1`?

**Comment by d-rk** [comment]
Hey @cykl 

If you look at the commit history you will see that the `1` was introduced in the initial commit. So, no it was not a deliberate choice 😃 

According to [this comment](https://github.com/IBM/sarama/blob/228c94e423f068fa75293e12f68cb6cf249d38d3/create_topics_request.go#L117) in the sarama lib, it should be safe (and a better default) to use `-1` instead.
