### ISSUE TITLE
Option to read value from a file

### ISSUE THREAD

**Issue by rkurniawati** [deviceinsight/kafkactl#189]
Hello,

I use `kafkactl` daily, often to send complex protobuf messages. `kafkactl` can handle this, but the JSON has to be in a single line which is long, not very readable, and prone to typing errors. For example, to send a `NestedMessage` (defined in the attached `nested-msg.proto.txt`), I have to use the following command line (or a JSON or CSV file with the key and value formatted in a single line):

```
kafkactl produce kafkactltest --key="Msg key" --value-proto-type NestedMessage \
  --proto-file testutil/testdata/nested-msg.proto  \
  --value='{ "customer_info" : {  "customer_id" : "12345",  "customer_name" : {   "first_name" : "Bob",   "last_name" : "Hound"  },  "address" : "101 Kennel Rd, Pound, AK" }, "device_info": {  "serial" : "abcde",  "last_update" : "2024-03-02T07:01:02.000Z" }}'
```

After examining the source code, I added a `--value-file` option that allows `kafkactl` to read the value from a file. With this option, the command line above becomes the much simpler:

```
kafkactl produce kafkactltest --key="Msg key" --value-proto-type NestedMessage \
  --proto-file testutil/testdata/nested-msg.proto  --value-file testutil/testdata/nested-msg.json
```

The content of nested-msg.json is below:
```json
{
    "customer_info" :
    {
        "customer_id" : "12345",
        "customer_name" : {
            "first_name" : "Bob",
            "last_name" : "Hound"
        },
        "address" : "101 Kennel Rd, Pound, AK"

    },
    "device_info": {
        "serial" : "abcde",
        "last_update" : "2024-03-02T07:01:02.000Z"
    }
}
```

If you think this new option may be useful for others, I'd be happy to open a PR to contribute the [changes](https://github.com/deviceinsight/kafkactl/compare/main...rkurniawati:kafkactl:main). I'll be sure to add test cases before opening the PR. 

Thanks!
Ruth

[nested-msg.proto.txt](https://github.com/deviceinsight/kafkactl/files/14474323/nested-msg.proto.txt)

**Comment by d-rk** [comment]
Hey @rkurniawati ,

I'm wondering if the additional parameter is needed. I think the same can already be achieved with the existing parameters.
If you use the `--file` parameter to provide your (multiline) json file, you just have to add the parameter `--lineSeparator` as well.
Per default the `--lineSeparator` splits on line endings (`\n`), but if you change it to a char sequence which is not contained in your json e.g. ` --lineSeparator ###`, the whole file is treated as one value.

So in your example you should be able to achieve the same with this:
```
kafkactl produce kafkactltest --key="Msg key" --value-proto-type NestedMessage \
  --proto-file testutil/testdata/nested-msg.proto  --file testutil/testdata/nested-msg.json --lineSeparator ###
```

Perhaps it is already sufficient to extend the README with usage examples on how to produce multiline json values.

Regards,
Dirk

**Comment by rkurniawati** [comment]
Thanks for the suggestion, Dirk! I was able to get `--file` along with `--lineSeparator` and `--separator` options to work for this scenario with only minor modifications to the input file (below). As an added bonus, this allows me to add multiple key/value pairs with a single command :)

```
kafkactl produce kafkactltest --value-proto-type=NestedMessage \
  --proto-file=testutil/testdata/nested-msg.proto \
  --lineSeparator='---' --separator='##'  \
  --file=testutil/testdata/nested-msg-kv.csv --input-format=csv
```

The content of nested-msg-kv.csv: 
```
Msg key##
{
    "customer_info": {
        "customer_id": "12345",
        "customer_name": {
            "first_name": "Bob",
            "last_name": "Hound"
        },
        "address": "101 Kennel Rd, Pound, AP"
    },
    "device_info": {
        "serial": "abcde",
        "last_update": "2024-03-02T07:01:02.000Z"
    }
}
---
```

I can open a PR with this info in the README file if you want -- just let me know.

Ruth

**Comment by d-rk** [comment]
ok cool, if you like to improve the README for this part, a PR is always welcome.
