### ISSUE TITLE
Facing issue with new configuration of kafkactl in centos server

### ISSUE THREAD

**Issue by Dinesh4683** [deviceinsight/kafkactl#199]
We have installed kafkactl in centos server with Kerberos enabled and after installed when we try to configure we are getting the below error.

Centos version -7.9
Confluent kafka - 5.5 (Open Source)

**Configuration:**

cat .config/kafkactl/config.yml
contexts:
    kafka-cluster:
        brokers:
            - xxxx:9092
 
current-context: kafka-cluster

Error Details:

afkactl get brokers -C .config/kafkactl/config.yml --verbose
[kafkactl] 2024/06/03 15:03:12 cannot find project config file: kafkactl.yml
[kafkactl] 2024/06/03 15:03:12 cannot find project config file: .kafkactl.yml
[kafkactl] 2024/06/03 15:03:12 Using config file: .config/kafkactl/config.yml
[kafkactl] 2024/06/03 15:03:12 Assuming kafkaVersion: 2.5.0
[kafkactl] 2024/06/03 15:03:12 Assuming kafkaVersion: 2.5.0
[kafkactl] 2024/06/03 15:03:12 using default admin request timeout: 3s
[sarama  ] 2024/06/03 15:03:12 Initializing new client
[sarama  ] 2024/06/03 15:03:12 client/metadata fetching metadata for all topics from broker xxxx:9092
[sarama  ] 2024/06/03 15:03:12 Connected to broker at xxxx:9092 (unregistered)
[sarama  ] 2024/06/03 15:03:12 Error while sending ApiVersionsRequest to broker xxxx:9092: unexpected EOF
[sarama  ] 2024/06/03 15:03:12 client/metadata got error from broker -1 while fetching metadata: unexpected EOF
[sarama  ] 2024/06/03 15:03:12 Closed connection to broker xxxx:9092
[sarama  ] 2024/06/03 15:03:12 client/metadata no available broker to send metadata request to
[sarama  ] 2024/06/03 15:03:12 client/brokers resurrecting 1 dead seed brokers

**Comment by d-rk** [comment]
Hey @Dinesh4683 

hard to tell whats going wrong here. You could specific the kafkaVersion explicitly in the config file and check if it makes a difference.
Apart from that you should check the logs of the broker, because the `unexpected EOF` should generate some related logs there.

**Comment by d-rk** [comment]
closing stale issue

**Comment by Winand** [comment]
I have a similar issue with Kafka 2.0.
Kafkactl assumes that we connect to Kafka 2.5 by default. Explicitly setting KAFKAVERSION=2.0.0 fixes the issue.
```
[kafkactl] 2025/01/15 15:12:59 cannot find project config file: kafkactl.yml
[kafkactl] 2025/01/15 15:12:59 cannot find project config file: .kafkactl.yml
[kafkactl] 2025/01/15 15:12:59 generated default config at /.config/kafkactl/config.yml
[kafkactl] 2025/01/15 15:12:59 Using config file: /.config/kafkactl/config.yml
[kafkactl] 2025/01/15 15:12:59 Assuming kafkaVersion: 2.5.0
[kafkactl] 2025/01/15 15:12:59 Assuming kafkaVersion: 2.5.0
[kafkactl] 2025/01/15 15:12:59 using default admin request timeout: 3s
[kafkactl] 2025/01/15 15:12:59 using isolationLevel=1
[sarama  ] 2025/01/15 15:12:59 Initializing new client
[sarama  ] 2025/01/15 15:12:59 client/metadata fetching metadata for all topics from broker my-broker-1:1234
[sarama  ] 2025/01/15 15:12:59 Connected to broker at my-broker-1:1234 (unregistered)
[sarama  ] 2025/01/15 15:12:59 Error while sending ApiVersionsRequest to broker my-broker-1:1234: kafka: insufficient data to decode packet, more bytes expected
[sarama  ] 2025/01/15 15:12:59 client/metadata got error from broker -1 while fetching metadata: EOF
[sarama  ] 2025/01/15 15:12:59 Closed connection to broker my-broker-1:1234
.................
[sarama  ] 2025/01/15 15:12:59 client/metadata no available broker to send metadata request to
[sarama  ] 2025/01/15 15:12:59 client/brokers resurrecting 3 dead seed brokers
[sarama  ] 2025/01/15 15:12:59 Closing Client
failed to create client: kafka: client has run out of available brokers to talk to: 3 errors occurred:
        * EOF
        * EOF
        * EOF
```
