### ISSUE TITLE
Add --context flag

### ISSUE THREAD

**Issue by cykl** [deviceinsight/kafkactl#214]
Kafkactl currently supports multiple contexts. To use a context, one must use `kubectl config use-context aws-dev`. 

This is often fine, but it also has following drawbacks:

* Active context is not explicit in a command line. You must know the active context to asset what a command will do.
* It's often annoying having to type two commands when one could suffice. 

Have you ever thought about introducing a --context flag (similar to kubectl). An explicit `--context` would take precedence over anything else. People enjoying how it works today can continue to do so, and people who prefer to set the context with every command will be happy to.

**Comment by cykl** [comment]
Thanks for the feedback. 

That's a good excuse to learn some go. I'll submit a PR.

**Comment by mzealey** [comment]
Yes really useful for us also. `use-context` requires having write permissions on the config file which we don't want to give.
