### ISSUE TITLE
Add a parameter `--tail` to consume command

### ISSUE THREAD

**Issue by dwi-di** [deviceinsight/kafkactl#27]
for development purposes it would be useful to have an option to get the latest `n` messages from a topic.
This would allow to simply check the format of the messages on the topic or to see if a message has been produced in the last minutes.

In order to find out which messages are the latest `n` we will have to read the latest `n` messages for each partition and afterwards sort/filter them based on the timestamp in the header.

**Comment by sarafecadu** [comment]
Can I take a crack at this one?

**Comment by dwi-di** [comment]
since no one is currently working on it, we would be happy if you could contribute this.

**Comment by dwi-di** [comment]
we needed the feature. so we already have a PR for it

**Comment by sarafecadu** [comment]
Fair enough. I should have followed up when I got busy a few weeks back. Glad you went forward.
