### ISSUE TITLE
Insecure TLS Config?

### ISSUE THREAD

**Issue by esiqveland** [deviceinsight/kafkactl#38]
Hi, and thank you for a great tool for helping manage kafka!

We have a setup where kafka runs with TLS setup. The certificates that the brokers use _are_ signed by our own CA, but we have to connect by IP so the hostname validation will always fail.

I made a small modification to `kafkactl` to be able to skip certificate validation entirely, and a slightly larger one to be able to only verify the certificate, but ignore Hostname Verification/SAN verification.

Is this something you would be interested in adding? I think it would be good to support the second variation with only CA signature verification, but I am not sure how to express this in the configuration, where as the first option is much simpler configuration wise.

Note that kafka brokers also implement this second scheme, see configuration parameter `ssl.endpoint.identification.algorithm` from broker configuration.

What do you think?

Thanks again for a great tool!

**Comment by dwi-di** [comment]
Hi,

I think both modifications are valuable for kafkactl. I saw you already opened a PR for the first one.
Just open a second one for skipping the hostname verification and we will come up with a solution on how the configuration can look like.

**Comment by dwi-di** [comment]
Hi @esiqveland,
are you still planning to submit a PR for skipping the hostname verification? otherwise I would close this issue.

**Comment by esiqveland** [comment]
No I can close this issue.
I can reopen if I do this after all.
