### ISSUE TITLE
Running `kafkactl config use-context` gets rid of comments

### ISSUE THREAD

**Issue by ateijelo** [deviceinsight/kafkactl#47]
Switching contexts using the command `kafkactl config use-context` will rewrite the config file and remove all comments. Comments may be in the configuration for documentation, or during experimentation.

**Comment by random-dwi** [comment]
we are using https://github.com/spf13/viper for configuration file management.
it would either have to be supported by viper directly or we would have to implement our own method for writing config files back.
Currently we have no plans to implement this, but PR is always welcome :)
