### ISSUE TITLE
Shell completion should honor `-C other-config.yaml`

### ISSUE THREAD

**Issue by ateijelo** [deviceinsight/kafkactl#48]
If a different config file is used with `-C` and shell completion is attempted:

```
kafkactl -C other-config.yaml consume <TAB><TAB>
```

the results from the completion are determined using the default config file.

I'm talking to two Kafka clusters using kafkactl in two separate terminal windows, so doing `use-context` every time is not practical. I separated the configs in two files and I pass it with `-C`, but the completions I'm getting come from the default one.

**Comment by random-dwi** [comment]
As a workaround you can try setting the config as environment variable:
```
export KAFKA_CTL_CONFIG=other-config.yaml
kafkactl consume <TAB><TAB>
```
Actually I'm waiting for spf13/cobra#1070 to be merged.
When this is done the auto completion can be improved and better aligned for the different shells.

**Comment by d-rk** [comment]
since there is a workaround for this and it is probably not that common to use multiple configs anyway. I will close this one
