### ISSUE TITLE
Add headers in producer

### ISSUE THREAD

**Issue by SteveGit007** [deviceinsight/kafkactl#50]
Hi,

Is it possible to add **headers** when producing messages with **kafakctl produce topic xxx**

Thanks !

**Comment by random-dwi** [comment]
Hi @SteveGit007,
at the moment headers can be consumed but not produced. It would be a good if this would be supported as well.
It should be pretty straight forward to implement it though.
The [ProducerMessage type](https://godoc.org/github.com/Shopify/sarama#ProducerMessage) has a Headers field that could be set.
The ProducerMessage is generated in two places [here](https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/DefaultMessageSerializer.go#L13) and [here](https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/AvroMessageSerializer.go#L89)

Are you interested in contributing this?

**Comment by SteveGit007** [comment]
Hi @deviceinsight/kafkactl<mailto:reply@reply.github.com>,

Thank you for your response.

Unfortunately I don't have enough time to participate in the project.

Sorry!

Kind regards,
Steve



De : random-dwi <notifications@github.com>
Envoyé : 2 juin 2020 02:57
À : deviceinsight/kafkactl <kafkactl@noreply.github.com>
Cc : SteveGit007 <steve_onmsn@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [deviceinsight/kafkactl] Add headers in producer (#50)


Hi @SteveGit007<https://github.com/SteveGit007>,
at the moment headers can be consumed but not produced. It would be a good if this would be supported as well.
It should be pretty straight forward to implement it though.
The ProducerMessage type<https://godoc.org/github.com/Shopify/sarama#ProducerMessage> has a Headers field that could be set.
The ProducerMessage is generated in two places here<https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/DefaultMessageSerializer.go#L13> and here<https://github.com/deviceinsight/kafkactl/blob/master/operations/producer/AvroMessageSerializer.go#L89>

Are you interested in contributing this?
