### ISSUE TITLE
Allow setting TLS config on commandline

### ISSUE THREAD

**Issue by MadsRC** [deviceinsight/kafkactl#55]
It would be very handy if one could set some of the TLS parameters using the command-line (Such as `enabled: true` and `insecure: false`). That would allow one-off invocations of `kafkactl` against brokers that only speak TLS (Such as Amazon MSK).

It is currently not possible, forcing one to create a config for one-off invocations.

**Proposal**: Extend kafkactl to allow take a flag indicating TLS and a flag indicating that certificate should be ignored. Example: `kafkactl -B somebroker:9094 --tls --insecure get topics --lag`

**Comment by random-dwi** [comment]
Hey,
Could you explain your usecase a bit more?
Are you running kafkactl in docker?
You want to talk to different clusters but only so rarely that you don't want it in your config?
In your PR you extend the default config generation so you will end up having it in your config anyway.
I'm not sure what you actually need.

**Comment by MadsRC** [comment]
Yes, of course!

I am currently dealing with a few Kafka clusters running in Amazon MSK. When running Amazon MSK, the Kafka cluster is only available from inside your VPC, meaning that I can't connect to it from a development machine.

It could be deployed by running `kafkactl` from a machine inside the VPC. The VPC's I'm running only contains Kubernetes clusters, so I'd have to deploy a dedicated machine for `kafkactl`.

Instead of doing that, I usually run `kafkactl` inside a pod in Kubernetes. However, starting a one-off container in Kubernetes containing a specific config file is cumbersome and not something I'd ever ask a junior engineer to do, so I'm looking for an easier approach.

I'm only using `kafkactl` to talk to one Kafka cluster per Kubernetes cluster. Each run of `kafkactl` will create a new container, and ideally I'd like to provide all the necessary configuration as environment variables or switches.

My PR does end up extending the default config. Mainly because it's the Fastest Way to Value. It works, since I know every run `kafkactl` will contain no config, and the generated config will be discarded after execution (New container every time).
