### ISSUE TITLE
kafkactl consume does not support consumer group/topic -G parameter

### ISSUE THREAD

**Issue by pierre-degrandmaison** [deviceinsight/kafkactl#60]
Kafka consumer-groups are to used by consumer applications, but "kafkactl consume" does not support any consumer-group/topic parameter 

(feature similar to other project "kafkacat -C -G <group ID> <topic>)

**Comment by random-dwi** [comment]
That's right, we have not needed this feature until now.
But we will put it on the roadmap.

**Comment by pierre-degrandmaison** [comment]
thanks, is the roadmap & milestones published somewhere?

**Comment by pierre-degrandmaison** [comment]
wrong button... :) reopen
