### ISSUE TITLE
Compile released binary with CGO=0

### ISSUE THREAD

**Issue by stefan-hudelmaier** [deviceinsight/kafkactl#8]
Hi, 

when I try to execute the provided binary on CentOS 7, I get 

`kafkactl: error while loading shared libraries: libgo.so.13: cannot open shared object file: No such file or directory`

I think it would be convenient if the provided binaries were compiled using CGO=0 to get around issues like that.

Regards,
Stefan

**Comment by dwi-di** [comment]
releaser are now done automatically with goreleaser on travis ci. this issue is taken care of
