### ISSUE TITLE
Kafkactl doesn't work in current version with kubernetes

### ISSUE THREAD

**Issue by cbrand** [deviceinsight/kafkactl#87]
I tried to run kafkactl in version 1.17.1 with a kubernetes backed config.

Unfortunately that fail due to an imagePull issue. Checking the implementation it looks like it is trying to download `1.17.1-scratch`, but on dockerhub only `v1.17.1-scratch` is available.

**Comment by random-dwi** [comment]
Can you please post the output of:
```
kafkactl get topics -V
```

**Comment by cbrand** [comment]
Here you go:

```
➜  ~ kafkactl get topics -V
[kafkactl] 2021/06/07 20:26:51 Using config file: ...
[kafkactl] 2021/06/07 20:26:51 Assuming kafkaVersion: 2.0.0
[kafkactl] 2021/06/07 20:26:51 kubectl version: 1.21.0
[kafkactl] 2021/06/07 20:26:51 exec: kubectl run --rm -i --tty --restart=Never kafkactl-bnd9qanckp --image deviceinsight/kafkactl:1.17.1-scratch --kubeconfig {redacted} --context {redacted} --namespace {redacted} --env BROKERS=kafka-headless:29092 --env KAFKAVERSION=2.0.0 --command -- /kafkactl get topics --verbose=true
error: timed out waiting for the condition
command "/usr/bin/kubectl" exited with non-zero status:

PATH:
  /usr/bin/kubectl

ARGS:
  0: kubectl (7 bytes)
  1: run (3 bytes)
  2: --rm (4 bytes)
  3: -i (2 bytes)
  4: --tty (5 bytes)
  5: --restart=Never (15 bytes)
  6: kafkactl-bnd9qanckp (19 bytes)
  7: --image (7 bytes)
  8: deviceinsight/kafkactl:1.17.1-scratch (37 bytes)
  9: --kubeconfig (12 bytes)
  10: {redacted} (30 bytes)
  11: --context (9 bytes)
  12: {redacted} (24 bytes)
  13: --namespace (11 bytes)
  14: {redacted} (16 bytes)
  15: --env (5 bytes)
  16: BROKERS=kafka-headless:29092 (28 bytes)
  17: --env (5 bytes)
  18: KAFKAVERSION=2.0.0 (18 bytes)
  19: --command (9 bytes)
  20: -- (2 bytes)
  21: /kafkactl (9 bytes)
  22: get (3 bytes)
  23: topics (6 bytes)
  24: --verbose=true (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

```

I looked a bit furhter though and think te issue doesn't reside inside of the actual code. I am using manjaro linux and the package seems to set the packageversion wrong: https://aur.archlinux.org/packages/kafkactl
According to the username I pressume that you published the package on aur?

Changing on https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kafkactl#n25

From
```
go build -ldflags "-linkmode=external -X github.com/deviceinsight/kafkactl/cmd.Version=${pkgver}" -o ${pkgname} .
```

To
```
go build -ldflags "-linkmode=external -X github.com/deviceinsight/kafkactl/cmd.Version=v${pkgver}" -o ${pkgname} .
```

and rebuilding the package fixes this for me.

**Comment by random-dwi** [comment]
Thank you for the analysis. 
The aur package is updated during the release via github action. So this line here needs to be modified:
https://github.com/deviceinsight/kafkactl/blob/76b506fbfffadf15601191a2aa0f060c4b792f1b/.github/aur/kafkactl/PKGBUILD.template#L25

**Comment by random-dwi** [comment]
@cbrand I just released a new version with a fix for this
