### ISSUE TITLE
validate-only should return an error when attempting to alter a topic to its current state

### ISSUE THREAD

**Issue by ernstae** [deviceinsight/kafkactl#92]
I'm using `kafkactl` as an methodology to add, update and delete topics with some puppet automation around it.  I'm relying on the `--validate-only` flag to return `0` so that I can proceed with the requested change.  However, if I pass in an alteration on a topic that actually matches the current state, I would expect for `--validate-only` to throw an error because it's not possible to alter a topic to the current state by removing the `--validate-only` argument from the command.

For example, if I wanted to increase the partition count from `1` to `2`, I would do something like this:

```
# kafkactl describe topic ernst
CONFIG                     VALUE
min.insync.replicas        1
segment.bytes              1073741824
message.format.version     2.4-IV1

PARTITION     OLDEST_OFFSET     NEWEST_OFFSET     LEADER                              REPLICAS     IN_SYNC_REPLICAS
0             0                 0                 kfk001:9091     1            1

# kafkactl alter topic ernst --replication-factor 1 --partitions 2 --validate-only
PARTITION     OLDEST_OFFSET     NEWEST_OFFSET     LEADER                              REPLICAS     IN_SYNC_REPLICAS
0             0                 0                 kfk001:9091     1            1
1             0                 0                                                     2

# echo $?
0

# kafkactl alter topic ernst --replication-factor 1 --partitions 2
partitions have been created
partition replicas have been reassigned
```

That brings us to this point, where I would like to test whether I could change to 2 partitions, and the `--validate-only` returns a 0.  I'd expect that the validation would say, "This is already the current state, so here's a non-zero return code", since when you attempt to actually run without the `--validate-only` flag, you will receive an error from kafkactl.

```
# kafkactl alter topic ernst --replication-factor 1 --partitions 2 --validate-only
PARTITION     OLDEST_OFFSET     NEWEST_OFFSET     LEADER                              REPLICAS     IN_SYNC_REPLICAS
0             0                 0                 kfk001:9091     1            1
1             0                 0                 kfk002:9091     2            2

# echo $?
0
```

So, now without `--validate-only`, I would expect that this would run correctly, since it validated correctly (but it doesn't).

```
# kafkactl alter topic ernst --replication-factor 1 --partitions 2
Could not create partitions for topic 'ernst': kafka server: Number of partitions is invalid. - Topic already has 2 partitions.

# echo $?
1
```

The specific logic that I'm trying to use is as follows (in a Puppet ERB template, but that's besides the point -- just throwing it in here for context.
```
if /usr/local/bin/kafkactl alter topic <%= v1['name'] %> --replication-factor ${REPLICATION_FACTOR} --partitions ${PARTITION_COUNT} <% unless v1['additional_params'].nil? -%><%=  v1['additional_params'] %><% end -%> --validate-only ${KAFKACFG_FILE} 2>&1 > /dev/null; then
    /usr/local/bin/kafkactl  alter topic <%= v1['name'] %> --replication-factor ${REPLICATION_FACTOR} --partitions ${PARTITION_COUNT} <% unless v1['additional_params'].nil? -%><%=  v1['additional_params'] %><% end %> ${KAFKACFG_FILE}
fi

```

**Comment by random-dwi** [comment]
Hey @ernstae ,

The AlterConfigs Request in the Kafka Protocol, has an option to call it with `validate_only` flag [(see here)](http://kafka.apache.org/protocol.html#The_Messages_AlterConfigs). Since the Request without this flag will throw an error, the right fix would be that kafka itself also throws an error with the flag set.
 But calling this with an unchanged number of partitions does not generate an error.

Since getting this changed in kafka itself, will not be that easy I just added a commit that verifies the partition count in kafkactl and throws an appropriate error before doing the AlterConfigs request.

**Comment by ernstae** [comment]
Thanks @random-dwi - Thank you for such a quick change!  I was going to wait till the weekend and consider contributing a patch, but 💯 for quick service!  Much appreciated!  Thank you!
